In [3]:
import numpy as np

#### Write a Python program to print the NumPy version in your system.

In [10]:
np.version.version

'1.19.2'

#### Write a Python program to reverse an array (first element becomes last).

In [14]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
rev_arr = array[::-1]
rev_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Write a Python program to convert a list and tuple into arrays.

In [6]:
lst = list(range(15))
lst_arr = np.array(lst)
lst_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
tpl = (23,3,45,67,76,54,90,87,67)
tpl_arr = np.array(tpl)
tpl_arr

array([23,  3, 45, 67, 76, 54, 90, 87, 67])

#### Write a Python program to find common values between two arrays.

In [46]:
arr1 = np.arange(3,9)
arr2 = np.arange(5,11)
np.intersect1d(arr1, arr2)

array([5, 6, 7, 8])

#### Write a Python program compare two arrays using numpy.

In [35]:
arr1 = np.random.rand(5)
arr2 = np.random.rand(5)
print('array1 elements are less than array2 elements: ',arr1<arr2)
print('array2 elements are less than array1 elements: ',arr1<arr2)
print('array1 elements are equal to array2 elements: ',arr1<arr2)

array1 elements are less than array2 elements:  [ True  True False False  True]
array2 elements are less than array1 elements:  [ True  True False False  True]
array1 elements are equal to array2 elements:  [ True  True False False  True]


#### Write a Python program to change the dimension of an array.

In [50]:
arr1 = np.arange(3,9)
print(arr1)
print(arr1.ndim)
arr1 = arr1.reshape(2,3)
print(arr1)
print(arr1.ndim)

[3 4 5 6 7 8]
1
[[3 4 5]
 [6 7 8]]
2


#### Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

In [67]:
array3 = np.arange(3,100,3)
array5 = np.arange(5,100,5)
sum_all = np.add(np.sum(array3),np.sum(array5))
sum_all

2633

#### Write a Python program to convert a NumPy array into Python list structure.

In [37]:
arr = np.arange(10)
lst = [i for i in arr]
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Write a Python program to how to add an extra column to a numpy array.

In [95]:
array = np.zeros((4,4))
np.hstack((array, np.ones(4).reshape(4,1)))

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

#### Write a Python program to check whether the numpy array is empty or not.

In [72]:
a = np.linspace(1,100,20)
np.size(a)==0

False

#### Write a Python program to normalize a 3x3 random matrix.

In [99]:
matrix = np.random.rand(9).reshape(3,3)
norm = np.linalg.norm(matrix)
matrix = matrix/norm
matrix

array([[0.32881515, 0.3053564 , 0.00237299],
       [0.42745815, 0.33532236, 0.43770615],
       [0.2181274 , 0.42452808, 0.28996647]])

#### How to ignore all numpy warnings (not recommended)?

In [38]:
np.seterr(all='ignore')
a = np.arange(3)
a/0

array([nan, inf, inf])

#### How to swap two rows of an array?

In [36]:
arr = np.arange(10).reshape(2,5)
print('Array before swap \n', arr)
arr[[0,1]] = arr[[1,0]]
print('Array after swap \n', arr)

Array before swap 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array after swap 
 [[5 6 7 8 9]
 [0 1 2 3 4]]


#### Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

array([0, 1, 2])

#### Python program to create a random vector of size 10 and sort it.

In [25]:
vector = np.random.rand(10)
print("matrix before sorting \n", vector)
print("matrix after sorting \n", np.sort(vector))

matrix before sorting 
 [0.865676   0.71784818 0.85039129 0.17990827 0.17634534 0.61917101
 0.43876619 0.23580034 0.67896119 0.50612881]
matrix after sorting 
 [0.17634534 0.17990827 0.23580034 0.43876619 0.50612881 0.61917101
 0.67896119 0.71784818 0.85039129 0.865676  ]


#### Write a Python program to check two random arrays are equal or not.

In [20]:
array1 = np.random.rand(9).reshape(3,3)
array2 = np.random.rand(9).reshape(3,3)
print(array1)
print(array2)
array1==array2

[[0.48419349 0.6837387  0.40160694]
 [0.29922172 0.84941011 0.28259795]
 [0.02189954 0.61243209 0.24104868]]
[[0.69535096 0.29813229 0.41840003]
 [0.10275067 0.92776836 0.88147508]
 [0.58454815 0.21707544 0.02306177]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

#### Write a Python program to add, subtract, multiply, divide arguments element-wise.

In [29]:
a = np.arange(6).reshape(2,3)
b = (np.arange(6)-7).reshape(2,3)
print('Array-1\n', a)
print('Array-2\n', b)
print('Add\n', a+b)
print('Subtract\n', a-b)
print('Multiply\n',a*b)
print('Divide\n',a/b)

Array-1
 [[0 1 2]
 [3 4 5]]
Array-2
 [[-7 -6 -5]
 [-4 -3 -2]]
Add
 [[-7 -5 -3]
 [-1  1  3]]
Subtract
 [[7 7 7]
 [7 7 7]]
Multiply
 [[  0  -6 -10]
 [-12 -12 -10]]
Divide
 [[-0.         -0.16666667 -0.4       ]
 [-0.75       -1.33333333 -2.5       ]]


#### Write a Python program to get the dates of yesterday, today and tomorrow.

In [15]:
today = np.datetime64('today','D')
print("Today's date: ",today)
yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yesterday's date: ",yesterday)
tomorrow = np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow's date: ",tomorrow)

Today's date:  2021-04-18
Yesterday's date:  2021-04-17
Tomorrow's date:  2021-04-19
